<a href="https://colab.research.google.com/github/BlackHole3344/Deep-learning/blob/main/CustomerChurnPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
df.drop(columns = ["RowNumber" , "CustomerId" , "Surname"] , inplace = True)


KeyError: "['RowNumber', 'CustomerId', 'Surname'] not found in axis"

In [7]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [9]:
# one hot encoding
df = pd.get_dummies( df , columns = ["Geography" , "Gender"] , drop_first= True)

In [10]:
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1        101348.88       1                  0   
1                  1        112542.58       0                  0   
2                  0        113931.57       1                  0   
3                  0         93826.63       0                  0   
4                  1         79084.10       0                  0   
...              ...              ...     ...                ...   
9995               0         96270.64       0                  0   
9996               1        101699.77       0                  0   
9997               1         42085.58       1                  0   
9998               0         92888.52       1                  1   
9999               0         38190.78       0                  0   

      Geography_Spain  Gender_Male  
0                   0            0  
1                   1            0  
2                   0            0  
3                   0            0  
4                   1            0  
...               ...          ...  
9995                0            1  
9996                0            1  
9997                0            0  
9998                0            1  
9999                0            0  

[10000 rows x 12 columns]

In [11]:
# now spliting the data
X = df.drop(columns = ["Exited"])
y = df["Exited"]

In [15]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split( X, y ,test_size = 0.3 , random_state = 1)

In [16]:
X_train.shape , X_test.shape

((7000, 11), (3000, 11))

In [18]:
# standardization , scaling the values
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()

X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.fit_transform(X_test)

In [21]:
X_train_scaled.shape

(7000, 11)

In [22]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [23]:
# Neural Network Structure
model = Sequential()
model.add(Dense(3 , activation = "sigmoid" , input_dim = 11))
model.add(Dense (1 ,activation = "sigmoid"))

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 36        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 40 (160.00 Byte)
Trainable params: 40 (160.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [27]:
# model complilation
model.compile(loss = "binary_crossentropy" , optimizer="Adam")

In [28]:
model.fit(X_train_scaled , y_train , epochs = 10)

Epoch 1/10
219/219 [==============================] - 3s 3ms/step - loss: 0.7687
Epoch 2/10
219/219 [==============================] - 1s 4ms/step - loss: 0.6126
Epoch 3/10
219/219 [==============================] - 1s 4ms/step - loss: 0.5360
Epoch 4/10
219/219 [==============================] - 1s 4ms/step - loss: 0.4973
Epoch 5/10
219/219 [==============================] - 1s 3ms/step - loss: 0.4754
Epoch 6/10
219/219 [==============================] - 1s 3ms/step - loss: 0.4615
Epoch 7/10
219/219 [==============================] - 1s 3ms/step - loss: 0.4516
Epoch 8/10
219/219 [==============================] - 1s 3ms/step - loss: 0.4440
Epoch 9/10
219/219 [==============================] - 1s 3ms/step - loss: 0.4381
Epoch 10/10
219/219 [==============================] - 1s 3ms/step - loss: 0.4335


In [33]:
# to get the weights and biases
model.layers[1].get_weights()

[array([[ 0.67600083],
        [ 0.4926841 ],
        [-1.8186324 ]], dtype=float32),
 array([-0.72393566], dtype=float32)]

In [34]:
# lets do predictions
model.predict(X_test_scaled)


94/94 [==============================] - 0s 1ms/step


array([[0.12581435],
       [0.17209306],
       [0.15132977],
       ...,
       [0.12765488],
       [0.19472302],
       [0.11674044]], dtype=float32)

In [37]:
y_log = model.predict(X_test_scaled)
import numpy as np

94/94 [==============================] - 0s 2ms/step


In [39]:
y_pred = np.where(y_log > 0.5 , 1 , 0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [40]:
# checking the accuracy of the model
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.8083333333333333